<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPpqnebu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpqnebu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPpqnebu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPpqnebu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPpqnebu\appDevDebugProjectContainer([
    'container.build_hash' => 'Ppqnebu',
    'container.build_id' => '15d29042',
    'container.build_time' => 1549922856,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpqnebu');
